spring.application.name=creator
spring.config.import=optional:file:./.env.properties

# BASE PROPERTIES
trial.signals.base-url=${base_url:base url not found}
trial.signals.api-key=${api_key:api key not found}

# TYPES
trial.signals.locationtype.kühlschrank=
trial.signals.locationtype.fach=
trial.signals.locationtype.tray=


# FIELDS
trial.signals.fields.

# DATABANK
spring.datasource.url=jdbc:postgresql://localhost:5430/data
spring.datasource.username=user
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true